export const DepictItCards = [
    "Screaming inside your heart",
    "Guineapig lab technicians",
    "Bum bongos",
    "Ritual sacrifice",
    "Making an onion cry",
    "Throwing starfish",
    "Awkward family photo",
    "Drunk fly",
    "Ugly crying",
    "Fighting fire with fire",
    "Racing a sloth",
    "A man hiding in a pram",
    "Side boob",
    "Playing the drums with chicken drumsticks",
    "Cats playing cats cradle",
    "Spontaneous human combustion",
    "Butt chin",
    "Glued to the screen",
    "Blowing smoke up someone's ass",
    "Toddler beauty pageant",
    "Winning 2nd prize in a beauty content",
    "Trapped in a phone box",
    "Putting make-up on an owl",
    "The world's biggest sneeze",
    "Watching paint dry",
    "Brain freeze",
    "Brain fart",
    "Haunted Oven",
    "Dancing on someone's grave",
    "Amoeba disco",
    "Falling apart",
    "Pinnocchio the pop star",
    "Abducted by amoeba",
    "Chubby bunny",
    "Face-plant",
    "Waiting in for a delivery",
    "Brushing your tongue",
    "A disappointing Christmas",
    "Photocopying your butt",
    "Forgetting how to eat",
    "Worm God",
    "Snail racing driver",
    "Licking boots",
    "Laughing your ass off",
    "Bad parkour",
    "Badly trained dentist",
    "A bizarre gardening accident",
    "Pooping in a urinal",
    "Scary snowman",
    "Stranger danger!",
    "Holiday in Hell",
    "Bad babysitter",
    "Stud muffin",
    "The curliest of moustaches",
    "Shower spider",
    "House husband",
    "Frisbee decapitation",
    "Free Willy",
    "Cowboy wrestling",
    "Rolling a cheese down a hill",
    "Staring contest",
    "Eye-wateringly strong pickles",
    "Love handles",
    "Sausage fingers",
    "Killing two birds with one stone",
    "Toenail fungus",
    "Happy slap",
    "Pooping on a bird",
    "Polishing a turd",
    "Biting off more than you can chew",
    "Cereal killer",
    "Cleaing out your pipes",
    "Costing an arm and a leg",
    "Fear of toilets",
    "Lost in a ball pit",
    "Self-portrait",
    "Bad trip",
    "Jumping out of your skin",
    "Trimming your neighbour's bush",
    "You scratch my back, I'll scratch yours",
    "Too much acid",
    "Smelly pits",
    "Arseless chaps",
    "Your vegetable friend",
    "Suitcase aquarium",
    "Combing your hair with a hedgehog",
    "Tramp stamp",
    "The Hiemlich maneuver",
    "Dad dancing",
    "Robin Hood and his merry hen",
    "Centaur lollipop man",
    "Exploding cuckoo clock",
    "Florida Man",
    "Unicorn rainbow fart",
    "Pet rock",
    "Seeing a man about a horse",
    "Horse tornado",
    "Beer goggles",
    "Every man and his dog",
    "Washing your mouth out with soap",
    "DIY lobotomy",
    "Trust excercises",
    "Tickle a pickle",
    "Clown police line-up",
    "Chicken crossing the road",
    "Running away from your problems",
    "Awkward hug",
    "Questionable content",
    "Perfect parenting",
    "An unfortunate birthmark",
    "Going postal",
    "Overlarge oven mitts",
    "Supernanny",
    "Saying 'No' to the dress",
    "The Fork Museum",
    "Foam party",
    "Up shit creek without a paddle",
    "Cat got your tongue",
    "Rubbernecking",
    "Bikeshedding",
    "Talking shit",
    "Ironing a char-pei",
    "Embarassing x-ray",
    "Stealing the covers",
    "Cheese dream",
    "Standing on Lego",
    "Angry birds",
    "Lord of the springs",
    "Where the sun don't shine",
    "Wiping the smile off your face",
    "Angry barbecue",
    "Octopus mating season",
    "Muffin top",
    "Sex bomb",
    "Bunny boiler",
    "Spooning a spoon",
    "Damp squib",
    "Tinder creep",
    "Slow day at the box factory",
    "Monkey business",
    "Really ugly baby",
    "High five a frog",
    "Kazoo orchestra",
    "Going out in a blaze of glory",
    "Cannibal finger buffet",
    "Drowing in someone's eyes",
    "Lactose intolerance",
    "Kicking the bucket",
    "LARPing",
    "Velociraptor Jesus",
    "Bronies",
    "Sore loser",
    "Freezing your own head",
    "Bingo wings",
    "I.T. rage",
    "Yer a wizard Larry!",
    "A red herring",
    "Rage quit",
    "Terrified by butter",
    "Shotgun wedding",
    "Eyeball golf",
    "Banana hammock",
    "Cow tipping",
    "Builders breakdancing",
    "Joyless clowns",
    "Stealing someone's thunder",
    "Lost in IKEA",
    "Throwing the baby out with the bathwater",
    "What really happened to the dinosaurs",
    "Beating around the bush",
    "Dutch oven",
    "A loving pat on the head",
    "The blind leading the blind",
    "The bee's knees",
    "OAP conga line",
    "A botched job",
    "Dark matter",
    "Space Jam",
    "S.T.D. Appreciation Day",
    '"Kitten Mittens" (TM)',
    "Naked statue of yourself",
    "Crying over spilt milk",
    "Netflix and chill",
    "A Cheeky Nandos",
    "Making an arse of yourself",
    "Beating up a jellyfish",
    "Going at it like rabbits",
    "Enterprise waterfall",
    "Potty mouth",
    "Minesweeping",
    "Eating roadkill",
    "Wheelbarrow race",
    "Gastric band",
    "Old man shouts at cloud",
    "Walking into a mirror",
    "Mr. Floppy",
    "Salad Fingers",
    "Riding a weasel",
    "Dreaming of bacon",
    "A dog's dinner",
    "Dogs dressed as humans",
    "Pulling a hat out of a rabbit",
    "The Trump family",
    "Personal space invasion",
    "Some slight chafing",
    "Constipation",
    "A throne of lies",
    "Edible underwear",
    "Babe magnet",
    "Farting in a lift",
    "Back acne",
    "A hovercraft full of eels",
    "Wandering hands",
    "Touching cloth",
    "Meat sweats",
    "Life giving you lemons",
    "Fight club",
    "Scaring yourself silly",
    "Booty call",
    "Raised by squirrels",
    "Drooling in your sleep",
    "Jazz hands",
    "Badly drawn on eyebrows",
    "Disappointing gravestone",
    "Crying on the inside",
    "A little slap and tickle",
    "Getting fingered by the law",
    "Chicken surprise",
    "Skeleton in your closet",
    "Neckbeard",
    "Jingle bells, Batman smells",
    "Heavy breathing",
    "Man spreading",
    "Darth Vader's day job",
    "Jumping on a sandcastle",
    "Swordfish fencing",
    "Chess boxing",
    "Giraffe limbo contest",
    "Getting in the sea",
    "Fainting goats",
    "T-Rex with a brand new handbag",
    "Rubbing someone up the wrong way",
    "Finger Lickin' Good!",
    "The duck face",
    "Moobs",
    "Sharknado",
    "Sexting",
    "Burger nips",
    "Llama poodle",
    "Adopting a cactus",
    "Death by salmon",
    "One foot in the grave",
    "Cakes on a train",
    "A cunning plan",
    "Crocodile tears",
    "Full of beans",
    "Covered in bees!"
];